openapi: 3.0.0
info:
  title: Tshirt store api
  description: Ecommerce api for tshirt store
  version: 1.0.0
  contact:
    email: abhin1509@gmail.com
    url: "https://github.com/abhin1509/tshirtstore"

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for local host
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /dummy:
    get:
      tags: # instead of default we can group, eg: string
        - string
      summary: returns a greet message from Abhinav
      responses:
        200:
          description: All good and success
          content:
            application/json:
              schema:
                type: string
                example: "mystring"
        400:
          description: Bad request
        500:
          description: internal server error
